built_in.h: improved to define DEFFILEMODE if not provided by the libc
musl libc doesn't provide the non-standard macros for common mode bit masks,
which other libc implementations like glibc define in <sys/stat.h>.

Compile time error when building against musl libc
--------------------------------------------------------------------------
netsniff-ng.c: In function 'read_pcap':
netsniff-ng.c:592:33: error: 'DEFFILEMODE' undeclared (first use in this function)
--------------------------------------------------------------------------

This change improves built_in.h to check if DEFFILEMODE is defined and if not
it defines it to be available internally.