trafgen: setup_shared_var: fix couple of things
1) Fix a couple of sparse warnings:
 trafgen.c:382:27: error: cannot size expression
 trafgen.c:391:33: error: cannot size expression
 trafgen.c:393:33: error: cannot size expression
 trafgen.c:401:25: error: cannot size expression
2) Use MAP_FAILED instead of (void *) -1
3) No need to cast to void * on mmap(2)
4) Use NULL instead of 0 as mmap(2)'s first argument

Signed-off-by: Daniel Borkmann <dborkman@redhat.com>