proc.h: add missing headers
ino_t and pid_t require stat.h and types.h, respectively. Fixes the following
build failure with musl libc:

In file included from cpp.c:7:0:
proc.h:11:31: error: unknown type name =E2=80=98ino_t=E2=80=99
 extern int proc_find_by_inode(ino_t ino, char *cmdline, size_t len, pid_t =
*pid);
                               ^
proc.h:11:69: error: unknown type name =E2=80=98pid_t=E2=80=99
 extern int proc_find_by_inode(ino_t ino, char *cmdline, size_t len, pid_t =
*pid);
                                                                     ^
proc.h:12:25: error: unknown type name =E2=80=98pid_t=E2=80=99
 extern bool proc_exists(pid_t pid);
                         ^

Signed-off-by: Baruch Siach <baruch@tkos.co.il>
[tk: complementary fix to commit a9f4431e0a20]
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>