ioops: fix build error by renaming 'len' variable
Argh, forgot to rename variables in read_blob_or_die/write_blob_or_die.

ioops.c: In function ‘read_blob_or_die’:
ioops.c:105:30: error: ‘len’ undeclared (first use in this function)
ioops.c:105:30: note: each undeclared identifier is reported only once for each function it appears in
ioops.c: In function ‘write_blob_or_die’:
ioops.c:116:31: error: ‘len’ undeclared (first use in this function)
make: *** [netsniff-ng/ioops.o] Error 1

Signed-off-by: Daniel Borkmann <dborkman@redhat.com>